// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { isProduction } from "./src/utils/isProduction.js";

const isProd = isProduction();
const DATABASE_URL = isProd ? process.env["DATABASE_URL"] : process.env["DATABASE_DEV_URL"];

if (!DATABASE_URL) throw new Error("DATABASE_URL not found");

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: DATABASE_URL,
  },
});
